spring.application.name=spendwise
spring.config.import=optional:file:./.env[.properties]

# Conexão com o PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/spendwise_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:MINHASENHACORRETA}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true